// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: network.proto
package com.fomin.demo.retrofit.bean;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 设备类型
 */
public enum PBDeviceType implements WireEnum {
  /**
   * 安卓
   */
  DEVICE_ANDROID(0),

  /**
   * 苹果
   */
  DEVICE_IOS(1),

  /**
   * PC
   */
  DEVICE_PC(2);

  public static final ProtoAdapter<PBDeviceType> ADAPTER = new ProtoAdapter_PBDeviceType();

  private final int value;

  PBDeviceType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBDeviceType fromValue(int value) {
    switch (value) {
      case 0: return DEVICE_ANDROID;
      case 1: return DEVICE_IOS;
      case 2: return DEVICE_PC;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_PBDeviceType extends EnumAdapter<PBDeviceType> {
    ProtoAdapter_PBDeviceType() {
      super(PBDeviceType.class);
    }

    @Override
    protected PBDeviceType fromValue(int value) {
      return PBDeviceType.fromValue(value);
    }
  }
}
