// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: network.proto
package com.fomin.demo.retrofit.bean;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * 网络类型
 */
public enum PBNetworkType implements WireEnum {
  /**
   * 未知网络
   */
  NET_UNKNOWN(0),

  /**
   * WIFI
   */
  NET_WIFI(1),

  /**
   * 2G网络
   */
  NET_2G(2),

  /**
   * 3G网络
   */
  NET_3G(3),

  /**
   * 4G网络
   */
  NET_4G(4);

  public static final ProtoAdapter<PBNetworkType> ADAPTER = new ProtoAdapter_PBNetworkType();

  private final int value;

  PBNetworkType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static PBNetworkType fromValue(int value) {
    switch (value) {
      case 0: return NET_UNKNOWN;
      case 1: return NET_WIFI;
      case 2: return NET_2G;
      case 3: return NET_3G;
      case 4: return NET_4G;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_PBNetworkType extends EnumAdapter<PBNetworkType> {
    ProtoAdapter_PBNetworkType() {
      super(PBNetworkType.class);
    }

    @Override
    protected PBNetworkType fromValue(int value) {
      return PBNetworkType.fromValue(value);
    }
  }
}
